-- Create the workout_logs table
create table workout_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  exercise_name text not null,
  weight numeric,
  reps text,
  actual_reps integer,
  set_number integer,
  notes text
);

-- Enable Row Level Security (RLS)
alter table workout_logs enable row level security;

-- Create a policy that allows anyone to insert (since we are using anon key for this simple app)
-- In a real app with auth, you would restrict this to authenticated users
create policy "Enable insert for all users" on workout_logs for insert with check (true);

-- Create a policy that allows anyone to select
create policy "Enable select for all users" on workout_logs for select using (true);
